### ISSUE TITLE
"@party" can't use on Reforged 8.0.2

### ISSUE THREAD

**Issue by BlueSoar** [HHServers/PixelChat#1]
https://paste.ubuntu.com/p/HnhZK3n8RV/
it can’t show party in pixelmon 8.0.2

**Comment by zbouvier** [comment]
the issue is that it is sending null pokemon, If you have a full team it sends just fine.

**Comment by HHServers** [comment]
I'll try and push an update out when I have some time

**Comment by HHServers** [comment]
fixed in 5b8bbb144fd42ee3a1cedc38d4fd0c9ccf569bca
