### ISSUE TITLE
Pixel Chat Crash

### ISSUE THREAD

**Issue by BlankSans** [HHServers/PixelChat#3]
I am start server and get this error

[latest.log](https://github.com/HHServers/PixelChat/files/5756839/latest.log)

**Comment by HHServers** [comment]
I will try and push an update tonight

**Comment by BlankSans** [comment]
Pixelmon Reforged 8.1.2

**Comment by HHServers** [comment]
@BlankSans could you try with the latest update I released on Ore?

**Comment by BlankSans** [comment]
Thanks.Its working
